import {sampleWorld} from "../world-data.js";
import {CANONICAL_DIRT_ID,createCanonicalDirtProduction,DIRT_CAPABILITY_VERSION,RAMP_TYPES,sampleCanonicalDirt,validateDirtRules} from "./canonical.js";
import {buildExpansionPlan,DIRT_PROFILES,mapRouteDistance,resolveExpansionProfile} from "./expansion.js";

const OPERATIONS=Object.freeze(["dirt.capabilities","dirt.inspectWorld","dirt.listLandmasses","dirt.inspectLandmass","dirt.inspectRules","dirt.listProfiles","dirt.inspectProvenance","dirt.listFeatures","dirt.inspectFeature","dirt.inspectExpansion","dirt.inspectIntervals","dirt.mapCoordinates","dirt.explainMapping","dirt.sampleTerrain","dirt.inspectCollision","dirt.inspectLOD","dirt.inspectChunk","dirt.inspectPerformance","dirt.explainAt","dirt.traceDecision","dirt.diffWorldScales","dirt.planCanonical","dirt.previewCanonical","dirt.validateCanonical","dirt.planRampRegeneration","dirt.diffRampRegeneration","dirt.planExpansion","dirt.planAppearance","dirt.planGroundTuning","dirt.validatePlan","dirt.previewPlan","dirt.commitPlan","dirt.undo","dirt.diagnosticBundle"]);
const MUTATIONS=new Set(["dirt.commitPlan","dirt.undo"]),MAX_PAGE=100,MAX_SAMPLES=256;
const clone=value=>structuredClone(value);
const error=(code,message,details={})=>({status:"error",capabilityVersion:DIRT_CAPABILITY_VERSION,error:{code,message,...details}});
const ok=(operation,revision,result)=>({status:"ok",capabilityVersion:DIRT_CAPABILITY_VERSION,operation,revision,result});
const featureView=(feature,worldId="current")=>{const profile=DIRT_PROFILES[worldId],linear={current:1,bigger:5,massive:32}[worldId];if(!profile||!linear)throw new Error("INVALID_PROFILE");return {...feature,worldOverview:{x:feature.canonical.x*linear,z:feature.canonical.z*linear},physicalGeometry:{...feature.geometry},geometryScaled:false};};

export function createDirtState(saved={}){
  const source=sampleWorld(),rules=validateDirtRules(saved.rules||{}),production=createCanonicalDirtProduction(source,rules);
  return {schemaVersion:DIRT_CAPABILITY_VERSION,projectId:saved.projectId||"demo-world",revision:saved.revision||0,rules,policy:saved.policy||{mode:"inherit-world"},production,history:saved.history||[]};
}

/** One transport-neutral, permission/revision checked dirt core. */
export class DirtWorldCore{
  constructor(state=createDirtState(),permissions={creator:["inspect","plan","commit","undo"],agent:["inspect","plan"],debugger:["inspect"]}){this.state=state;this.permissions=permissions;}
  execute(request){
    try{return this.#execute(request);}catch(cause){const code=String(cause.message).split(":")[0];return error(code.includes("_")?code:"INVALID_REQUEST",cause.message);}
  }
  #execute(request){
    if(!request||request.schemaVersion!==DIRT_CAPABILITY_VERSION||!OPERATIONS.includes(request.operation))return error("INVALID_REQUEST","Use a supported dirt-v1 operation.");
    const grants=this.permissions[request.actorId]||[],needed=MUTATIONS.has(request.operation)?(request.operation==="dirt.undo"?"undo":"commit"):request.operation.includes("plan")||request.operation.includes("preview")||request.operation.includes("validate")||request.operation.includes("Regeneration")?"plan":"inspect";
    if(!grants.includes(needed))return error("UNAUTHORIZED",`${request.actorId||"anonymous"} lacks ${needed}.`,{suggestedGrant:needed});
    if(request.projectId&&request.projectId!==this.state.projectId)return error("INVALID_REQUEST","projectId does not match opened project.");
    if(request.landmassId&&request.landmassId!==CANONICAL_DIRT_ID)return error("UNKNOWN_LANDMASS",request.landmassId);
    const op=request.operation,input=request.input||{},p=this.state.production,worldId=input.worldId||"current",plan=buildExpansionPlan(p,worldId,input.policy||this.state.policy);
    if(op==="dirt.capabilities")return ok(op,this.state.revision,{operations:OPERATIONS.map(id=>({id,implemented:true,grant:MUTATIONS.has(id)?"commit":id.includes("plan")?"plan":"inspect"})),limits:{page:MAX_PAGE,samples:MAX_SAMPLES,trace:32},coordinateSpaces:["canonical","world","experience","render-local"],adapters:["local-js","cli-json"],unsupported:["arbitrary-2d-warp","gpu-telemetry","automatic-upload","desktop-ipc","mcp"]});
    if(op==="dirt.inspectWorld")return ok(op,this.state.revision,{source:{mapId:p.sourceMapId,revision:p.sourceRevision,width:500,height:500},worlds:Object.values(DIRT_PROFILES).filter(x=>["current","bigger","massive"].includes(x.id)),protectedRegions:p.protectedBounds,topology:"finite canonical map; renderer repeats horizontally and vertically"});
    if(op==="dirt.listLandmasses")return ok(op,this.state.revision,{items:[this.#landmass()],total:1,nextOffset:null});
    if(op==="dirt.inspectLandmass")return ok(op,this.state.revision,this.#landmass());
    if(op==="dirt.inspectRules")return ok(op,this.state.revision,{stored:this.state.rules,effective:{...this.state.rules,expansion:plan.profile},provenance:{rules:"canonical-production",expansion:plan.profile.provenance},candidateCounts:p.generation.candidateCounts,probabilityMetric:p.generation.probabilityMetric});
    if(op==="dirt.listProfiles")return ok(op,this.state.revision,{items:Object.values(DIRT_PROFILES),total:Object.keys(DIRT_PROFILES).length});
    if(op==="dirt.inspectProvenance")return ok(op,this.state.revision,{landmassId:p.id,sourceMapId:p.sourceMapId,sourceRevision:p.sourceRevision,algorithmVersion:p.algorithmVersion,seed:p.rules.seed,derivedExpansionId:plan.id});
    if(op==="dirt.listFeatures"){const {offset=0,limit=25}=input;if(!Number.isInteger(offset)||!Number.isInteger(limit)||limit<1||limit>MAX_PAGE)throw new Error("QUERY_LIMIT_EXCEEDED");const items=p.features.slice(offset,offset+limit).map(f=>featureView(f,worldId));return ok(op,this.state.revision,{items,total:p.features.length,nextOffset:offset+items.length<p.features.length?offset+items.length:null});}
    if(op==="dirt.inspectFeature"){const f=p.features.find(x=>x.id===input.featureId);if(!f)throw new Error("UNKNOWN_FEATURE");return ok(op,this.state.revision,featureView(f,worldId));}
    if(op==="dirt.inspectExpansion")return ok(op,this.state.revision,{id:plan.id,policy:this.state.policy,effectiveProfile:plan.profile,sourceLength:plan.sourceLength,experienceLength:plan.experienceLength,fixedFeatures:p.features.length});
    if(op==="dirt.inspectIntervals")return ok(op,this.state.revision,this.#page(plan.intervals,input));
    if(op==="dirt.mapCoordinates"||op==="dirt.explainMapping"){const from=input.fromSpace||input.position?.space||"canonical",value=input.value??input.position?.distance,mapped=mapRouteDistance(plan,value,from);return ok(op,this.state.revision,{from,value,to:from==="canonical"?"experience":"canonical",mappedValue:mapped.value,interval:mapped.interval,effectiveProfile:plan.profile});}
    if(op==="dirt.sampleTerrain"||op==="dirt.explainAt"){const points=input.points||[input.position||{x:input.x,z:input.z}];if(points.length>MAX_SAMPLES)throw new Error("QUERY_LIMIT_EXCEEDED");const samples=points.map(point=>({...point,...sampleCanonicalDirt(p,point.x,point.z),coordinateSpace:input.coordinateSpace||"canonical",sourceRevision:p.sourceRevision,profileVersion:plan.profile.version,collisionAuthority:"canonical-height-sampler",visualLod:input.visualLod||"not-observed"}));return ok(op,this.state.revision,{samples});}
    if(op==="dirt.inspectCollision")return ok(op,this.state.revision,{authority:"canonical-height-sampler",prepared:true,sample:sampleCanonicalDirt(p,input.x,input.z),visualGeometryRequired:false});
    if(op==="dirt.inspectLOD")return ok(op,this.state.revision,{near:{step:4,collisionAuthority:true},far:{grid:112,collisionAuthority:false},status:"model-only; no live renderer telemetry",camera:input.viewId||"main"});
    if(op==="dirt.inspectChunk")return ok(op,this.state.revision,{address:input.address||null,state:"reconstructable",cacheTelemetry:"unavailable",deterministicKey:`${p.id}:${p.sourceRevision}:${plan.profile.version}:${input.address||"unspecified"}`});
    if(op==="dirt.inspectPerformance")return ok(op,this.state.revision,{budgets:{canonicalBytes:p.mask.byteLength,maxPreviewSamples:4096,maxApiSamples:MAX_SAMPLES},actual:{savedFeatures:p.features.length},gpuTelemetry:{available:false,reason:"headless core"}});
    if(op==="dirt.diffWorldScales")return ok(op,this.state.revision,{scales:["current","bigger","massive"].map(id=>({worldId:id,profile:resolveExpansionProfile(id,this.state.policy),features:p.features.slice(0,input.limit||10).map(f=>featureView(f,id))})),invariants:{sameCanonicalMask:true,sameFeatureIds:true,samePhysicalGeometry:true,gapsOnly:true}});
    if(op==="dirt.traceDecision")return ok(op,this.state.revision,{steps:[{code:"SOURCE_MASK",decision:"canonical-production",revision:p.sourceRevision},{code:"PROFILE_RESOLUTION",decision:plan.profile.mode,profile:plan.profile.id},{code:"COLLISION_AUTHORITY",decision:"canonical-height-sampler"}],truncated:false,limit:32});
    if(op==="dirt.planCanonical"||op==="dirt.planRampRegeneration"||op==="dirt.diffRampRegeneration"){const nextRules=validateDirtRules({...this.state.rules,...input.rules,candidateProbability:{...this.state.rules.candidateProbability,...input.candidateProbability}}),draft=createCanonicalDirtProduction(sampleWorld(),nextRules),diff=this.#featureDiff(draft);return ok(op,this.state.revision,{kind:"canonical-regeneration",baseRevision:this.state.revision,rules:nextRules,coverage:draft.coverage,featureDiff:diff,committable:true,cost:{sourceCells:250000,previewSamples:Math.min(input.maxPreviewSamples||4096,4096)}});}
    if(op==="dirt.planExpansion")return ok(op,this.state.revision,{kind:"expansion-policy",baseRevision:this.state.revision,policy:input.policy||this.state.policy,plan,committable:true,limitations:["one-dimensional main route; arbitrary 2D warp unsupported"]});
    if(op==="dirt.planAppearance"||op==="dirt.planGroundTuning")return ok(op,this.state.revision,{kind:"rules-patch",baseRevision:this.state.revision,rules:{...this.state.rules,...input.rules},committable:true,note:"shade settings do not modify height unless explicit height fields change"});
    if(op==="dirt.previewCanonical"||op==="dirt.previewPlan")return ok(op,this.state.revision,{nonMutating:true,view:input.view||"canonical-map",before:{revision:this.state.revision},after:input.plan||input,maxSamples:Math.min(input.maxSamples||1024,4096)});
    if(op==="dirt.validateCanonical"||op==="dirt.validatePlan")return ok(op,this.state.revision,{valid:input.plan?.baseRevision===undefined||input.plan.baseRevision===this.state.revision,diagnostics:input.plan?.baseRevision!==undefined&&input.plan.baseRevision!==this.state.revision?[{code:"STALE_REVISION"}]:[]});
    if(op==="dirt.commitPlan")return this.#commit(request,input.plan||input);
    if(op==="dirt.undo")return this.#undo(request,input);
    if(op==="dirt.diagnosticBundle")return ok(op,this.state.revision,{redacted:true,uploaded:false,source:{mapId:p.sourceMapId,revision:p.sourceRevision},algorithmVersion:p.algorithmVersion,seed:p.rules.seed,profile:plan.profile,features:p.features.slice(0,Math.min(input.limit||10,25)).map(f=>f.id),environment:{runtime:"local-js",privatePaths:false}});
    throw new Error("NOT_IMPLEMENTED");
  }
  #landmass(){const p=this.state.production;return {id:p.id,sourceMapId:p.sourceMapId,bounds:{x:0,y:0,width:500,height:500},coverage:p.coverage,protectedBounds:p.protectedBounds,featureCount:p.features.length,rules:p.rules,policy:this.state.policy,algorithmVersion:p.algorithmVersion};}
  #page(items,{offset=0,limit=25}){if(!Number.isInteger(offset)||!Number.isInteger(limit)||limit<1||limit>MAX_PAGE)throw new Error("QUERY_LIMIT_EXCEEDED");const page=items.slice(offset,offset+limit);return {items:page,total:items.length,nextOffset:offset+page.length<items.length?offset+page.length:null};}
  #featureDiff(next){const before=new Map(this.state.production.features.map(x=>[x.id,JSON.stringify(x)])),after=new Map(next.features.map(x=>[x.id,JSON.stringify(x)]));return {added:[...after.keys()].filter(x=>!before.has(x)),removed:[...before.keys()].filter(x=>!after.has(x)),modified:[...after.keys()].filter(x=>before.has(x)&&before.get(x)!==after.get(x))};}
  #commit(request,plan){if(request.expectedRevision!==this.state.revision)return error("STALE_REVISION","Commit expectedRevision is stale.",{actualRevision:this.state.revision});if(!request.operationId)return error("INVALID_REQUEST","operationId is required for commit.");if(plan.baseRevision!==this.state.revision)return error("STALE_REVISION","Plan is stale.");const previous={rules:this.state.rules,policy:this.state.policy};if(plan.kind==="canonical-regeneration"){this.state.rules=validateDirtRules(plan.rules);this.state.production=createCanonicalDirtProduction(sampleWorld(),this.state.rules);}else if(plan.kind==="expansion-policy"){resolveExpansionProfile(plan.worldId||"current",plan.policy);this.state.policy=clone(plan.policy);}else if(plan.kind==="rules-patch"){this.state.rules=validateDirtRules(plan.rules);this.state.production=createCanonicalDirtProduction(sampleWorld(),this.state.rules);}else return error("INVALID_REQUEST","Unknown reviewed plan kind.");this.state.revision++;const undoToken=`dirt-undo-${request.operationId}`;this.state.history.push({undoToken,operationId:request.operationId,revision:this.state.revision,previous});return ok("dirt.commitPlan",this.state.revision,{committed:true,undoToken,featureIds:this.state.production.features.map(f=>f.id)});}
  #undo(request,input){if(request.expectedRevision!==this.state.revision)return error("STALE_REVISION","Undo expectedRevision is stale.");const record=this.state.history.at(-1);if(!record||record.undoToken!==input.undoToken)return error("UNDO_CONFLICT","Only the latest dirt transaction may be undone.");this.state.rules=record.previous.rules;this.state.policy=record.previous.policy;this.state.production=createCanonicalDirtProduction(sampleWorld(),this.state.rules);this.state.history.pop();this.state.revision++;return ok("dirt.undo",this.state.revision,{undone:true,operationId:record.operationId});}
}

export class ProgrammerDirtApi extends DirtWorldCore{}
export class AgentDirtApi extends DirtWorldCore{}

export function serializeDirtState(state){return {schemaVersion:DIRT_CAPABILITY_VERSION,projectId:state.projectId,revision:state.revision,rules:state.rules,policy:state.policy,history:state.history};}
