import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import Ajv2020 from 'ajv/dist/2020.js';
import {AgentWorldApi} from '../src/world-api/agent.js';import {ProgrammerWorldApi,applyTransaction} from '../src/world-api/programmer.js';import {TERRAIN} from '../src/world-api/core.js';
const read=p=>JSON.parse(fs.readFileSync(new URL(`../${p}`,import.meta.url)));
const types=read('schemas/world-api-types-v1.schema.json'),inspection=read('schemas/world-api-inspection-v1.schema.json'),diagnostics=read('schemas/world-api-diagnostics-v1.schema.json');
const project=()=>({schemaVersion:1,projectId:'schema-test',revision:0,width:8,height:8,baseGround:Array(64).fill(TERRAIN.ocean),baseHeights:Array(64).fill(0),regions:[],permissions:{reader:['inspect'],writer:['inspect','commit','draft','export']},operationLog:[],undoStack:[]});
const aliases={'world-api-types-v1':types,'world-api-inspection-v1':inspection,'world-api-diagnostics-v1':diagnostics};
function resolve(id){const [name,fragment='']=id.split('#'),doc=aliases[name];assert.ok(doc,`advertised document exists: ${name}`);let value=doc;if(fragment){for(const part of fragment.replace(/^\//,'').split('/'))value=value[part.replaceAll('~1','/').replaceAll('~0','~')];}assert.ok(value,`advertised schema resolves: ${id}`);return value;}
test('every advertised schema resolves and representative concrete outputs validate',()=>{const p=project(),agent=new AgentWorldApi(p),programmer=new ProgrammerWorldApi(p),manifest=agent.inspectCapabilities('reader');const ajv=new Ajv2020({strict:false});for(const op of manifest.operations){resolve(op.inputSchemaId);resolve(op.outputSchemaId);}
 const validateInspection=ajv.compile(inspection);for(const output of [manifest,programmer.inspectMap('reader',{x:0,y:0,width:2,height:2}),programmer.explainCell('reader',{x:0,y:0}),agent.inspectRegions('reader',{limit:5})])assert.equal(validateInspection(output),true,JSON.stringify(validateInspection.errors));
 const operation=programmer.patchCells({id:'one',cells:[{x:1,y:1,terrainId:TERRAIN.grass,height:2}]});const result=applyTransaction(p,{schemaVersion:1,operationId:'schema',projectId:p.projectId,expectedRevision:0,actor:'writer',debug:'deep'},[operation]);const validateDiagnostic=ajv.compile(diagnostics);assert.equal(validateDiagnostic(result.diagnostics[0]),true,JSON.stringify(validateDiagnostic.errors));
});
