import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {sampleWorld, fromTiled, ID} from '../src/world-data.js';
import {AgentWorldApi} from '../src/world-api/agent.js';
import {ERROR_CODES, WorldApiError} from '../src/world-api/core.js';
import {applyTransaction, ProgrammerWorldApi, undoTransaction} from '../src/world-api/programmer.js';
import {exportTiled, initProject, saveProject} from '../scripts/world-api/project-io.mjs';

function project(){const world=sampleWorld();return {schemaVersion:1,projectId:'test',revision:0,width:500,height:500,baseGround:Array.from(world.ground),baseHeights:Array.from(world.heights),regions:[],permissions:{agent:['inspect','draft','commit','export'],programmer:['inspect','draft','edit','commit','export']},operationLog:[],undoStack:[]};}
const envelope=(operationId='op',actor='agent',revision=0)=>({schemaVersion:1,operationId,projectId:'test',expectedRevision:revision,actor});

test('agent surface plans deterministic explicit regions without mutating the project',()=>{const p=project(),api=new AgentWorldApi(p),request={...envelope('plan'),seed:27183,regions:[{id:'north',width:30,height:24,anchor:{area:'north'},lockedAfterAccept:true},{id:'west',width:24,height:24,anchor:{area:'west'}}]};const a=api.plan(request),b=api.plan(request);assert.deepEqual(a,b);assert.equal(a.operations.length,2);assert.equal(p.regions.length,0);assert.match(api.preview(a).artifact,/north/);});

test('programmer edit is visible to agent inspection and agent commit is visible to programmer geometry inspection',()=>{let p=project();const programmer=new ProgrammerWorldApi(p),op=programmer.patchCells({id:'exact',cells:[{x:10,y:11,terrainId:ID.dirt,height:123}]});let result=applyTransaction(p,envelope('program','programmer'),[op]);assert.ok(result.committed);p=result.project;assert.equal(new AgentWorldApi(p).inspect().regions[0].id,'exact');const plan=new AgentWorldApi(p).plan({...envelope('agent-plan','agent',1),seed:9,regions:[{id:'east',width:8,height:8,at:[400,400]}]});result=new AgentWorldApi(p).commit(envelope('agent-commit','agent',1),plan);p=result.project;const cells=new ProgrammerWorldApi(p).inspectMap({x:400,y:400,width:1,height:1});assert.equal(cells.cells[0].terrainId,ID.sand);assert.ok(cells.cells[0].height>0);});

test('collisions, locks and revision conflicts are machine-readable and atomic',()=>{let p=project(),api=new AgentWorldApi(p);const first=api.plan({...envelope('p1'),seed:1,regions:[{id:'locked',width:20,height:20,at:[50,50],lockedAfterAccept:true}]});p=api.commit(envelope('c1'),first).project;api=new AgentWorldApi(p);const collision=api.plan({...envelope('p2','agent',1),seed:2,regions:[{id:'overlap',width:10,height:10,at:[55,55]}]});assert.equal(collision.diagnostics[0].code,ERROR_CODES.locked);assert.equal(collision.operations.length,0);assert.throws(()=>api.commit(envelope('stale','agent',0),first),e=>e instanceof WorldApiError&&e.code===ERROR_CODES.revision);assert.equal(p.regions.length,1);});

test('commit rejects a direct operation that bypasses placement checks to replace a locked ID',()=>{let p=project();const locked=new ProgrammerWorldApi(p).patchCells({id:'locked',cells:[{x:7,y:8,terrainId:ID.grass,height:5}],locked:true});p=applyTransaction(p,envelope('create-lock','programmer'),[locked]).project;const before=structuredClone(p),replacement={type:'region.place',region:{...structuredClone(p.regions[0]),tiles:[ID.dirt],heights:[99],locked:false},previous:structuredClone(p.regions[0])};const result=applyTransaction(p,envelope('bypass-lock','programmer',1),[replacement]);assert.equal(result.committed,false);assert.equal(result.diagnostics[0].code,ERROR_CODES.locked);assert.deepEqual(result.project,before);assert.deepEqual(p,before);});

test('undo rejects unauthorized and stale direct calls without changing the project',()=>{let p=project(),op=new ProgrammerWorldApi(p).patchCells({id:'a',cells:[{x:1,y:1,terrainId:1,height:5}]});p=applyTransaction(p,envelope('undoable','programmer'),[op]).project;const before=structuredClone(p);assert.throws(()=>undoTransaction(p,envelope('unauthorized','intruder',1),'undo-undoable'),e=>e instanceof WorldApiError&&e.code===ERROR_CODES.permission);assert.deepEqual(p,before);assert.throws(()=>undoTransaction(p,envelope('stale-undo','programmer',0),'undo-undoable'),e=>e instanceof WorldApiError&&e.code===ERROR_CODES.revision);assert.deepEqual(p,before);});

test('operation IDs are idempotent and authorized latest transaction can be undone',()=>{let p=project(),op=new ProgrammerWorldApi(p).patchCells({id:'a',cells:[{x:1,y:1,terrainId:1,height:5}]});let result=applyTransaction(p,envelope('once','programmer'),[op]);p=result.project;result=applyTransaction(p,{...envelope('once','programmer',1)},[op]);assert.equal(result.idempotent,true);const undone=undoTransaction(p,envelope('undo-once-request','programmer',1),'undo-once');assert.equal(undone.regions.length,0);assert.equal(undone.revision,2);assert.equal(undone.operationLog.at(-1).actor,'programmer');});

test('500x500 project exports ordinary Tiled JSON and reimports terrain, elevations and stable IDs without changing sources',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'world-api-')),world=sampleWorld(),map={orientation:'orthogonal',width:500,height:500,tilewidth:32,tileheight:32,layers:[{name:'Ground',type:'tilelayer',data:Array.from(world.ground)}]};fs.writeFileSync(path.join(dir,'base.json'),JSON.stringify(map));fs.writeFileSync(path.join(dir,'elev.json'),JSON.stringify({width:500,height:500,values:Array.from(world.heights)}));let p=initProject(dir,{map:'base.json',elevation:'elev.json',id:'test'});p.permissions.programmer=['inspect','draft','edit','commit','export'];const sourceBefore=fs.readFileSync(path.join(dir,'base.json'),'utf8'),op=new ProgrammerWorldApi(p).patchCells({id:'placed',cells:[{x:250,y:250,terrainId:ID.grass,height:44}]});p=applyTransaction(p,envelope('exportable','programmer'),[op]).project;p.projectRoot=dir;p.baseMap=map;saveProject(p);const output=path.join(dir,'out.json'),info=exportTiled(p,output),loaded=fromTiled(JSON.parse(fs.readFileSync(output,'utf8')));assert.equal(loaded.ground[250*500+250],ID.grass);assert.equal(loaded.heights[250*500+250],44);assert.equal(fs.readFileSync(path.join(dir,'base.json'),'utf8'),sourceBefore);assert.equal(info.sha256.length,64);assert.equal(JSON.parse(fs.readFileSync(output)).substrateRegions[0].id,'placed');const reimportDir=fs.mkdtempSync(path.join(os.tmpdir(),'world-api-reimport-'));fs.copyFileSync(output,path.join(reimportDir,'world.json'));const reimported=initProject(reimportDir,{map:'world.json',id:'again'});assert.equal(reimported.regions[0].id,'placed');assert.equal(reimported.regions[0].heights[0],44);});
