import {assertEnvelope, clone, createDiagnosticContext, diagnostic, ERROR_CODES, TERRAIN, validateRegion, WorldApiError} from './core.js';
import {ProgrammerWorldApi, applyTransaction, projectProjection} from './programmer.js';
import {WorldInspection} from './inspection.js';

const hash=(text,seed)=>{let h=seed|0;for(const c of text)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0;};
function terrain(width,height,seed,id){const tiles=[],heights=[];for(let y=0;y<height;y++)for(let x=0;x<width;x++){const edge=Math.min(x,y,width-1-x,height-1-y),n=(hash(`${x},${y},${id}`,seed)%1000)/1000;tiles.push(edge<2?TERRAIN.sand:(n<.18?TERRAIN.dirt:TERRAIN.grass));heights.push(edge<2?1+n:3+n*3);}return {tiles,heights};}
function candidates(area,w,h,canvas){const slots={north:[Math.floor((canvas.width-w)/2),20],west:[20,Math.floor((canvas.height-h)/2)],east:[canvas.width-w-20,Math.floor((canvas.height-h)/2)],south:[Math.floor((canvas.width-w)/2),canvas.height-h-20],center:[Math.floor((canvas.width-w)/2),Math.floor((canvas.height-h)/2)]};return slots[area]||slots.center;}

/** Intent-oriented surface. Plans are explicit diffs; plan and preview never mutate project state. */
export class AgentWorldApi {
  constructor(project){this.project=project;this.programmer=new ProgrammerWorldApi(project);this.inspection=new WorldInspection(project);}
  inspectCapabilities(actor){return this.inspection.capabilities(actor);}
  inspectRegions(actor,options){return this.inspection.regions(actor,options);}
  inspectRegion(actor,id){return this.inspection.region(actor,id);}
  inspectOperations(actor,options){return this.inspection.operations(actor,options);}
  inspectPlacementSurface(actor,id){return this.inspection.placementSurface(actor,id);}
  explainCell(actor,cell){return this.inspection.cell(actor,cell);}
  inspect(actor){assertEnvelope({schemaVersion:1,operationId:'legacy-inspect',projectId:this.project.projectId,expectedRevision:this.project.revision,actor},this.project,'inspect');return {schemaVersion:1,projectId:this.project.projectId,revision:this.project.revision,canvas:{width:this.project.width,height:this.project.height,unit:'tiled-cell'},regions:this.inspection.regions(actor,{offset:0,limit:25}),regionsTruncated:this.project.regions.length>25,capabilities:['inspect','plan','preview','commit','undo','export','exact-map-patch']};}
  plan(request){assertEnvelope(request,this.project,'draft');const context=createDiagnosticContext(this.project,request,'plan');context.step('GRANT_AND_REVISION_CHECK','allow',{actor:request.actor,expectedRevision:request.expectedRevision});const seed=request.seed??0;if(!Number.isInteger(seed))throw new WorldApiError(ERROR_CODES.invalid,'seed must be an integer.');if(!Array.isArray(request.regions)||request.regions.length<1||request.regions.length>3)throw new WorldApiError(ERROR_CODES.capacity,'The v1 planner accepts one to three regions.', ['Split larger work into reviewed transactions.']);const operations=[],diagnostics=[],seen=new Set,planningProject=clone(this.project);for(let i=0;i<request.regions.length;i++){const spec=request.regions[i],width=spec.width??32,height=spec.height??32;let [x,y]=spec.at||candidates(spec.anchor?.area,width,height,this.project);if(!spec.at&&!spec.anchor?.area){x=20+(i*67)%(this.project.width-width-40);y=20+(i*83)%(this.project.height-height-40);}const generated=terrain(width,height,seed,spec.id);const region={id:spec.id,kind:spec.kind||'terrain-patch',bounds:{x,y,width,height},...generated,locked:Boolean(spec.lockedAfterAccept),provenance:{kind:'agent-plan',seed,referenceId:spec.referenceId||null,referenceUse:spec.referenceUse||'style-only'}};try{if(seen.has(region.id))throw new WorldApiError(ERROR_CODES.duplicate,`Region ID ${region.id} occurs more than once.`);seen.add(region.id);validateRegion(region,planningProject,region.id,context);operations.push({type:'region.place',region,previous:null});planningProject.regions.push(region);}catch(error){diagnostics.push(diagnostic(error,context));}}
    if(diagnostics.length)return {schemaVersion:1,kind:'world-plan',projectId:this.project.projectId,baseRevision:this.project.revision,seed,operations:[],diagnostics,alternatives:['Reduce region dimensions.','Supply non-overlapping at coordinates.']};
    return {schemaVersion:1,kind:'world-plan',projectId:this.project.projectId,baseRevision:this.project.revision,seed,operations,diagnostics:[],explanation:`Proposed ${operations.length} editable terrain-v1 regions; generated heights are authored proposals, not inferred from imagery.`};}
  preview(plan,{actor,width=1000,height=1000}={}){if(!actor)throw new WorldApiError(ERROR_CODES.invalid,'An actor is required for preview.');const grants=this.project.permissions?.[actor]||[];if(!grants.includes('draft'))throw new WorldApiError(ERROR_CODES.permission,`${actor} lacks draft permission.`);if(plan.baseRevision!==this.project.revision)throw new WorldApiError(ERROR_CODES.revision,'Plan was made against an older revision.');const colors=['','#75a85a','#8b6b42','#d9c27c','#185a86','#3187a8','#2877a1'];let shapes=`<rect width="100%" height="100%" fill="${colors[4]}"/>`;for(const op of plan.operations){const b=op.region.bounds;shapes+=`<rect x="${b.x/this.project.width*width}" y="${b.y/this.project.height*height}" width="${b.width/this.project.width*width}" height="${b.height/this.project.height*height}" fill="${colors[1]}" stroke="#fff"/><text x="${(b.x+2)/this.project.width*width}" y="${(b.y+8)/this.project.height*height}" fill="#fff" font-size="14">${escapeXml(op.region.id)}</text>`;}return {mediaType:'image/svg+xml',width,height,artifact:`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">${shapes}</svg>`,diagnostics:plan.diagnostics};}
  commit(request,plan){if(plan.baseRevision!==request.expectedRevision)throw new WorldApiError(ERROR_CODES.revision,'Plan revision does not match commit revision.');if(!Array.isArray(plan.diagnostics)||plan.diagnostics.length)return {project:this.project,revision:this.project.revision,committed:false,diagnostics:[diagnostic(new WorldApiError(ERROR_CODES.plan,'A plan with diagnostics cannot be committed.', ['Resolve the plan diagnostics and create a new plan.']))]};return applyTransaction(this.project,request,plan.operations);}
}
const escapeXml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
