#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {AgentWorldApi} from '../src/world-api/agent.js';
import {assertEnvelope, diagnostic} from '../src/world-api/core.js';
import {undoTransaction} from '../src/world-api/programmer.js';
import {atomicJson, exportTiled, initProject, loadProject, saveProject} from './world-api/project-io.mjs';
const json=file=>JSON.parse(fs.readFileSync(path.resolve(file),'utf8'));
function args(values){const out={_:[]};for(let i=0;i<values.length;i++){if(values[i].startsWith('--'))out[values[i].slice(2)]=values[++i];else out._.push(values[i]);}return out;}
export async function main(argv){const a=args(argv),command=a._[0],dir=path.resolve(a.project||'.');if(command==='init'){const project=initProject(dir,{map:a.map,elevation:a.elevation,id:a.id});return {projectId:project.projectId,revision:0,canvas:{width:project.width,height:project.height}};}const project=loadProject(dir),agent=new AgentWorldApi(project);if(command==='inspect')return agent.inspect();if(command==='plan'){const request=json(a.request),plan=agent.plan(request);atomicJson(path.resolve(a.out||'world.plan.json'),plan);return {plan:path.resolve(a.out||'world.plan.json'),regions:plan.operations.length,diagnostics:plan.diagnostics};}if(command==='preview'){const plan=json(a.plan),preview=agent.preview(plan);const out=path.resolve(a.out||'world-preview.svg');fs.writeFileSync(out,preview.artifact);return {preview:out,diagnostics:preview.diagnostics};}if(command==='commit'){const plan=json(a.plan),request=json(a.request),result=agent.commit(request,plan);if(result.committed)saveProject({...result.project,projectRoot:project.projectRoot,baseMap:project.baseMap,baseGround:project.baseGround,baseHeights:project.baseHeights});return {...result,project:undefined};}if(command==='undo'){const request=json(a.request);assertEnvelope(request,project,'commit');const next=undoTransaction(project,a.token,request.actor);saveProject(next);return {revision:next.revision,undone:true};}if(command==='export'){const request=json(a.request);assertEnvelope(request,project,'export');if(a.format&&a.format!=='tiled-json')throw Error('Only tiled-json export is supported in v1.');return exportTiled(project,path.resolve(a.out||'world-export.json'));}throw Error('Usage: world-api <init|inspect|plan|preview|commit|undo|export> --project DIR [options]');}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))main(process.argv.slice(2)).then(value=>console.log(JSON.stringify(value,null,2))).catch(error=>{console.error(JSON.stringify(diagnostic(error),null,2));process.exitCode=1;});

