#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {AgentWorldApi} from '../src/world-api/agent.js';
import {assertEnvelope, DEBUG_LEVELS, diagnostic, ERROR_CODES, WorldApiError} from '../src/world-api/core.js';
import {undoTransaction} from '../src/world-api/programmer.js';
import {atomicJson, exportTiled, initProject, loadProject, saveProject} from './world-api/project-io.mjs';
const json=file=>JSON.parse(fs.readFileSync(path.resolve(file),'utf8'));
function args(values){const out={_:[]};for(let i=0;i<values.length;i++){if(values[i].startsWith('--'))out[values[i].slice(2)]=values[++i];else out._.push(values[i]);}return out;}
export async function main(argv){const a=args(argv),command=a._[0],dir=path.resolve(a.project||'.');if(a.debug&&!DEBUG_LEVELS.includes(a.debug))throw new WorldApiError(ERROR_CODES.invalid,'--debug must be off, regular, or deep.');if(command==='init'){const project=initProject(dir,{map:a.map,elevation:a.elevation,id:a.id});return {projectId:project.projectId,revision:0,canvas:{width:project.width,height:project.height}};}const project=loadProject(dir),agent=new AgentWorldApi(project),actor=a.actor||'owner',paging={offset:Number(a.offset||0),limit:Number(a.limit||25)},withDebug=request=>({...request,debug:a.debug||request.debug||'off'});if(command==='inspect')return agent.inspect(actor);if(command==='capabilities')return agent.inspectCapabilities(actor);if(command==='inspect-map')return agent.programmer.inspectMap(actor,{x:Number(a.x||0),y:Number(a.y||0),width:Number(a.width||project.width),height:Number(a.height||project.height)});if(command==='explain-cell')return agent.explainCell(actor,{x:Number(a.x),y:Number(a.y)});if(command==='inspect-regions')return a.id?agent.inspectRegion(actor,a.id):agent.inspectRegions(actor,paging);if(command==='inspect-operations')return agent.inspectOperations(actor,paging);if(command==='inspect-surface')return agent.inspectPlacementSurface(actor,a.id);if(command==='plan'){const request=withDebug(json(a.request)),plan=agent.plan(request);atomicJson(path.resolve(a.out||'world.plan.json'),plan);return {plan:path.resolve(a.out||'world.plan.json'),regions:plan.operations.length,diagnostics:plan.diagnostics};}if(command==='preview'){const plan=json(a.plan),preview=agent.preview(plan,{actor});const out=path.resolve(a.out||'world-preview.svg');fs.writeFileSync(out,preview.artifact);return {preview:out,diagnostics:preview.diagnostics};}if(command==='commit'){const plan=json(a.plan),request=withDebug(json(a.request)),result=agent.commit(request,plan);if(result.committed)saveProject({...result.project,projectRoot:project.projectRoot,baseMap:project.baseMap,baseGround:project.baseGround,baseHeights:project.baseHeights});return {...result,project:undefined};}if(command==='undo'){const request=withDebug(json(a.request)),next=undoTransaction(project,request,a.token);saveProject(next);return {revision:next.revision,undone:true};}if(command==='export'){const request=withDebug(json(a.request));assertEnvelope(request,project,'export');if(a.format&&a.format!=='tiled-json')throw new WorldApiError(ERROR_CODES.invalid,'Only tiled-json export is supported in v1.');return exportTiled(project,path.resolve(a.out||'world-export.json'));}throw new WorldApiError(ERROR_CODES.invalid,'Usage: world-api <init|inspect|capabilities|inspect-map|explain-cell|inspect-regions|inspect-operations|inspect-surface|plan|preview|commit|undo|export> --project DIR [options]');}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const argv=process.argv.slice(2);main(argv).then(value=>console.log(JSON.stringify(value,null,2))).catch(error=>{const a=args(argv),projectId=a.project?path.basename(path.resolve(a.project)):null,context={phase:'cli',operationId:null,projectId,revision:null,debug:a.debug||'off',trace:[],truncated:false};console.error(JSON.stringify(error.diagnostic||diagnostic(error,context),null,2));process.exitCode=1;});}
